version: '3.8'

services:
  web:
    build: ./app/
    ports:
      - "8070:8080"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      SECRETCODE: ${SECRETCODE}
      FLAG: ${FLAG}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      TZ: Asia/Seoul
    volumes:
      - ./app/uploads:/uploads
      - ./app/src:/app
    restart: always
    env_file:
      - .env
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
